spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: cloud-config-dhjt-dev
---
spring:
  profiles: test
  application: cloud-config-dhjt-test
---
dhjt:
  name: dhjt
  email: dhjt11@qq.com
  time: '2019-10-07'