spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application: cloud-config-eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application: cloud-config-eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/